# Generated by Django 4.1.4 on 2023-01-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cureation_platform", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiuser",
            name="user_image",
            field=models.FileField(
                default="images/user_images/defaultUser.jpg",
                upload_to="images/user_images/",
            ),
        ),
    ]
